{% set name = "insightface" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/insightface-{{ version }}.tar.gz
  sha256: b8d9884f2358c51d297edb499e0a1fd15854ee89ff21740fffe339b0db0f3a9f

build:
  entry_points:
    - insightface-cli=insightface.commands.insightface_cli:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - numpy
    - cython
    - pypandoc
    - pip
    - libgl-devel                    # [linux]
  run:
    - python
    - onnx
    - onnxruntime
    - opencv
    - tqdm
    - requests
    - matplotlib-base
    - pillow
    - scipy
    - scikit-learn
    - scikit-image
    - easydict
    - cython
    - albumentations
    - prettytable

test:
  imports:
    - insightface
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepinsight/insightface
  summary: InsightFace Python Library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
